import { createClient } from "@/lib/supabase/client";
import { getAuthenticatedUserId, throwOnError } from "@/lib/dal";
export type ShiftStatus = "agendado" | "realizado" | "cancelado";
export type Shift = { id:string; user_id:string; place_id:string; data:string; hora_inicio:string; hora_fim:string; valor_previsto:number; status:ShiftStatus; created_at:string; updated_at:string };
export type ShiftInput = Omit<Pick<Shift,"place_id"|"data"|"hora_inicio"|"hora_fim"|"valor_previsto">, "valor_previsto"> & { valor_previsto: number | null; status?: ShiftStatus };
export type ShiftUpdate = Partial<ShiftInput>;
export async function listShifts():Promise<Shift[]>{const u=await getAuthenticatedUserId();const {data,error}=await createClient().from("shifts").select("*").eq("user_id",u).order("data",{ascending:false});await throwOnError(error);return (data??[]) as Shift[];}
export async function getShift(id:string):Promise<Shift|null>{const u=await getAuthenticatedUserId();const {data,error}=await createClient().from("shifts").select("*").eq("id",id).eq("user_id",u).maybeSingle();await throwOnError(error);return data as Shift|null;}
function normalize(input: ShiftInput | ShiftUpdate) { return Object.fromEntries(Object.entries(input).map(([key, value]) => [key, key === "valor_previsto" && value === "" ? null : value])); }
export async function createShift(input:ShiftInput):Promise<Shift>{const u=await getAuthenticatedUserId();const {data,error}=await createClient().from("shifts").insert({...normalize(input),user_id:u}).select("*").single();await throwOnError(error);return data as Shift;}
export async function updateShift(id:string,input:ShiftUpdate):Promise<Shift>{const u=await getAuthenticatedUserId();const {data,error}=await createClient().from("shifts").update(normalize(input)).eq("id",id).eq("user_id",u).select("*").single();await throwOnError(error);return data as Shift;}
export type ShiftObligationInput = ShiftInput & { data_prevista?: string | null; responsavel_place_id?: string | null; responsavel_contact_id?: string | null };
export async function saveShiftWithObligation(id:string|null,input:ShiftObligationInput):Promise<Shift>{await getAuthenticatedUserId();const {data,error}=await createClient().rpc("save_shift_with_obligation",{p_shift_id:id,p_place_id:input.place_id,p_data:input.data,p_hora_inicio:input.hora_inicio,p_hora_fim:input.hora_fim,p_valor_previsto:input.valor_previsto,p_status:input.status??"agendado",p_data_prevista:input.data_prevista??null,p_responsavel_place_id:input.responsavel_place_id??null,p_responsavel_contact_id:input.responsavel_contact_id??null});await throwOnError(error);return data as Shift;}
export async function removeShift(id:string):Promise<void>{const u=await getAuthenticatedUserId();const {error}=await createClient().from("shifts").delete().eq("id",id).eq("user_id",u);await throwOnError(error);}
