"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { getShift, type Shift } from "@/lib/shifts";
import { financialAmounts, listObligations, type Obligation } from "@/lib/obligations";
import { listPayments, removePayment, type Payment } from "@/lib/payments";
import { listPlaces } from "@/lib/places";
import { listContacts } from "@/lib/contacts";

const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const fmtDate = (v: string) => new Date(`${v}T12:00:00`).toLocaleDateString("pt-BR");
const labels = { agendado: "Agendado", realizado: "Realizado", cancelado: "Cancelado" } as const;
type Detail = { shift: Shift; obligation: Obligation | null; payments: Payment[]; place: string; responsible: string };

export default function ShiftDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const [detail, setDetail] = useState<Detail | null>(null); const [state, setState] = useState("loading"); const [id, setId] = useState(""); const [busy, setBusy] = useState("");
  async function load(shiftId: string) { setState("loading"); try { const shift = await getShift(shiftId); if (!shift) { setState("missing"); return; } const [os, ps, places, contacts] = await Promise.all([listObligations(), listPayments(), listPlaces(), listContacts()]); const o = os.find(x => x.shift_id === shift.id) ?? null; setDetail({ shift, obligation: o, payments: o ? ps.filter(x => x.obligation_id === o.id) : [], place: places.find(x => x.id === shift.place_id)?.nome ?? "Local não encontrado", responsible: o?.responsavel_place_id ? places.find(x => x.id === o.responsavel_place_id)?.nome ?? "Local não encontrado" : contacts.find(x => x.id === o?.responsavel_contact_id)?.nome ?? (o ? "Contato não encontrado" : "Não informado") }); setState("ready"); } catch { setState("error"); } }
  useEffect(() => { void params.then(p => { setId(p.id); void load(p.id); }); }, [params]);
  async function cancel(payment: Payment) { if (!confirm("Cancelar este pagamento?")) return; setBusy(payment.id); try { await removePayment(payment.id); await load(id); } finally { setBusy(""); } }
  if (state === "loading") return <main className="p-6" role="status">Carregando ficha do plantão...</main>;
  if (state === "missing") return <main className="space-y-4 p-6"><h1 className="text-2xl font-bold">Plantão não encontrado</h1><p>Este plantão não existe ou não pertence à sua conta.</p><Link href="/calendario" className="underline">Voltar ao calendário</Link></main>;
  if (state === "error" || !detail) return <main className="space-y-4 p-6"><h1 className="text-2xl font-bold">Ficha do plantão</h1><p role="alert">Não foi possível carregar este plantão.</p><Button onClick={() => void load(id)}>Tentar novamente</Button></main>;
  const { shift, obligation: o } = detail; const amounts = financialAmounts(shift.status, o); const progress = amounts.expected ? Math.min(100, amounts.received / amounts.expected * 100) : 0;
  return <main className="mx-auto max-w-3xl space-y-6 px-4 py-6 sm:px-6"><Link href="/calendario" className="inline-flex items-center gap-2 text-sm text-primary"><ArrowLeft className="size-4" /> Voltar ao calendário</Link><header><p className="text-sm text-muted-foreground">Ficha do plantão</p><h1 className="mt-1 text-3xl font-semibold">{detail.place}</h1><span className="mt-3 inline-block rounded-full bg-muted px-3 py-1 text-sm">{labels[shift.status]}</span></header><section className="grid gap-3 sm:grid-cols-2">{[["Data",fmtDate(shift.data)],["Horário",`${shift.hora_inicio.slice(0,5)} – ${shift.hora_fim.slice(0,5)}`],["Responsável",detail.responsible],["Local",detail.place]].map(([k,v]) => <div className="rounded-xl border bg-card p-4" key={k}><p className="text-sm text-muted-foreground">{k}</p><p className="mt-2 font-medium">{v}</p></div>)}</section>{shift.status !== "realizado" ? <section className="rounded-xl border bg-card p-5"><h2 className="font-semibold">Financeiro</h2><p className="mt-2 text-sm text-muted-foreground">{shift.status === "cancelado" ? "Plantões cancelados não entram no saldo." : "Plantão agendado sem obrigação não é uma dívida."}</p></section> : !o ? <section className="rounded-xl border border-dashed p-5"><h2 className="font-semibold">Obrigação financeira ausente</h2><p className="mt-2 text-sm text-muted-foreground">Este plantão realizado ainda não possui obrigação registrada.</p></section> : <section className="space-y-4 rounded-xl border bg-card p-5"><div><h2 className="font-semibold">Resumo financeiro</h2><p className="mt-1 text-sm text-muted-foreground">Data prevista: {fmtDate(o.data_prevista)}</p></div><div className="grid gap-3 sm:grid-cols-3">{[["Valor devido",amounts.expected],["Recebido",amounts.received],["Saldo",amounts.balance]].map(([k,v]) => <div className="rounded-lg bg-muted p-3" key={k}><p className="text-sm text-muted-foreground">{k}</p><p className="mt-1 font-semibold">{brl.format(v as number)}</p></div>)}</div><div aria-label={`Progresso: ${Math.round(progress)}% recebido`} className="h-3 overflow-hidden rounded-full bg-muted"><div className="h-full bg-emerald-500" style={{ width: `${progress}%` }} /></div><p className="text-sm text-muted-foreground">{Math.round(progress)}% recebido</p><h3 className="font-medium">Pagamentos</h3>{detail.payments.length === 0 ? <p className="text-sm text-muted-foreground">Nenhum pagamento registrado.</p> : detail.payments.map(p => <div className="flex justify-between border-t py-3 text-sm" key={p.id}><span>{brl.format(Number(p.valor))} · {fmtDate(p.data_pagamento)}{p.status === "cancelado" && " · cancelado"}</span>{p.status === "registrado" && <Button size="sm" variant="ghost" disabled={busy === p.id} onClick={() => void cancel(p)}>{busy === p.id ? "Cancelando..." : "Cancelar"}</Button>}</div>)}{amounts.balance > 0 && <Link href="/pagamentos" className="text-sm text-primary underline">Registrar pagamento</Link>}</section>}</main>;
}
