import type { ComponentProps, ReactNode } from "react";
import { cn } from "cn";

export function Card({ className, ...props }: ComponentProps<"div">) { return <div className={cn("rounded-2xl border bg-card text-card-foreground shadow-sm", className)} {...props} />; }
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <header className="flex flex-col gap-4 py-6 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight">{title}</h1>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{action}</header>; }
export function StatCard({ label, value, detail }: { label: string; value: ReactNode; detail?: string }) { return <Card className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{detail && <p className="mt-1 text-xs text-muted-foreground">{detail}</p>}</Card>; }
export function Badge({ children, tone = "neutral" }: { children: ReactNode; tone?: "neutral" | "success" | "warning" | "danger" }) { return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold", tone === "success" && "bg-emerald-100 text-emerald-700", tone === "warning" && "bg-amber-100 text-amber-700", tone === "danger" && "bg-red-100 text-red-700", tone === "neutral" && "bg-muted text-muted-foreground")}>{children}</span>; }
export function Input(props: ComponentProps<"input">) { return <input className="h-10 w-full rounded-lg border bg-background px-3 text-sm outline-none ring-offset-background placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring" {...props} />; }
export function Select(props: ComponentProps<"select">) { return <select className="h-10 w-full rounded-lg border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring" {...props} />; }
export function EmptyState({ title, description }: { title: string; description?: string }) { return <div className="rounded-2xl border border-dashed p-10 text-center"><p className="font-semibold">{title}</p>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>; }
export function Skeleton({ className }: { className?: string }) { return <div className={cn("animate-pulse rounded-lg bg-muted", className)} />; }
export function Money({ value }: { value: number }) { return <span>{new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value)}</span>; }
export function DateDisplay({ value }: { value: string | Date }) { return <time dateTime={new Date(value).toISOString()}>{new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium" }).format(new Date(value))}</time>; }
export function Dialog({ children, ...props }: ComponentProps<"dialog">) { return <dialog className="rounded-2xl border bg-background p-6 shadow-xl backdrop:bg-black/30" {...props}>{children}</dialog>; }
export function Sheet({ children, className, ...props }: ComponentProps<"div">) { return <div className={cn("fixed inset-y-0 right-0 z-50 w-full max-w-md border-l bg-background p-6 shadow-xl", className)} {...props}>{children}</div>; }
export function ConfirmDialog({ title, children }: { title: string; children: ReactNode }) { return <Dialog><h2 className="font-semibold">{title}</h2><div className="mt-2 text-sm text-muted-foreground">{children}</div></Dialog>; }
export function Toast({ children }: { children: ReactNode }) { return <div role="status" className="fixed bottom-5 right-5 z-50 rounded-xl border bg-background px-4 py-3 text-sm shadow-lg">{children}</div>; }
